"""Constants for the cluster protocol."""

APP: int = 828369
VERSION: int = 1
PORT: int = 5605
BUFFER_SIZE: int = 1024
NODE_AVAILABILITY_CHECK_INTERVAL: int = 35
MASTER_AVAILABILITY_CHECK_INTERVAL: int = 65
MASTER_PING_INTERVAL: int = 60
SLAVE_PING_INTERVAL: int = 15
